// THIS FILE IS AUTO-GENERATED BY utils/generate_exporter_help.go. DO NOT EDIT.

package main

const helpText = `USAGE:
Commands:

discover-ports:
  Show discovered ports and exit
loop-textfile:
  Writes all metrics to textfiles every loop-interval
    --loop-textfile-update-interval=30s
        Interval between textfiles updates

single-textfile:
  Writes all metrics to textfiles ONCE. Usefull for testing or crons


Flags:

Ethtool settings:
  --ethtool-path=/usr/sbin/ethtool
  --ethtool-timeout=5s
    Timeout for ethtool command execution.

Various paths settings:
  --linux-net-class-path=/sys/class/net
  --textfile-directory=/var/lib/node-exporter/textfiles
    Path to node_exporter textfile directory. Only used in 'single-textfile' and 'loop-textfile' modes

Collectors, enabled by default:
  --no-collect-generic-info-settings
  --no-collect-driver-info-common
  --no-collect-module-info-diagnostics-alarms
  --no-collect-module-info-diagnostics-warnings

Collectors, disabled by default:
  --collect-driver-info-features
  --collect-generic-info-modes
  --collect-module-info-diagnostics-values
  --collect-module-info-vendor

Port detection settings:
  --discover-allowed-port-types=1,
    Comma-separated list of allowed interface types (see if_arp.h). Set to empty ('') to allow all port types
  --discover-all-ports
    Force discover all ports, ignoring all the other discover flags, EXCEPT for 'discover-allowed-port-types' and 'discover-ports-regexp'
  --no-discover-bond-slaves
    Whether we discover ports that are enslaved by bonds
  --discover-ports-regexp=.+
    Only discover ports with names matching this regexp

Absent metrics settings:
  --keep-absent-metrics
    Set 'Nan' value for every metric that wasn't found

`
