// THIS FILE IS AUTO-GENERATED BY utils/generate_exporter_help.go. DO NOT EDIT.

package main

const helpText = `USAGE:
Commands:

discover-ports:
  Show discovered ports and exit
http-server:
  Starts HTTP server of scraping metrics over HTTP(S), like node-exporter does
    --web.listen-address=:9417
        Address on which to expose metrics

    --web.max-requests=3
        Maximum number of concurrent HTTP requests

loop-textfile:
  Writes all metrics to textfile every loop-interval
    --loop-textfile-update-interval=30s
        Interval between textfile updates

single-textfile:
  Writes all metrics to textfile ONCE. Usefull for testing or crons


Flags:

Ethtool settings:
  --path.ethtool=/usr/sbin/ethtool
  --ethtool-timeout=5s
    Timeout for ethtool command execution.

Various paths settings:
  --path.sysfs.net.class=/sys/class/net
  --path.textfile-directory=/var/lib/node-exporter/textfiles
    Path to the node_exporter textfile directory. Only used in 'single-textfile' and 'loop-textfile' modes

Collectors, enabled by default:
  --no-collect-generic-info-settings
  --no-collect-driver-info-common
  --no-collect-module-info-diagnostics-alarms
  --no-collect-module-info-diagnostics-warnings
  --collect-statistics-general

Collectors, disabled by default:
  --collect-all-metrics
    Ignores all the flags below. Usefull for testing
  --collect-driver-info-features
  --collect-generic-info-modes
  --collect-module-info-diagnostics-values
  --collect-module-info-vendor
  --collect-statistics-per-queue-general
  --collect-statistics-per-queue-per-type
  --collect-statistics-per-queue-xdp

Port detection settings:
  --discover-allowed-port-types=1,
    Comma-separated list of allowed interface types (see if_arp.h). Set to empty ('') to allow all port types
  --discover-all-ports
    Force discover all the ports, ignoring all the other discover flags, EXCEPT for 'discover-allowed-port-types' and 'discover-ports-regexp'
  --no-discover-bond-slaves
    Whether to discover ports that are enslaved by bonds
  --discover-bridge-slaves
    Whether to discover ports that are enslaved by bridges
  --discover-ports-regexp=.+
    Only discover ports with names matching this regexp

Absent metrics exposure. This controls how to expose missing metrics: via Nan values of the same metrics, via counter metrics, counting how many metrics are missing per collector, or via special per-metric metrics, exposing full missing label name via label:
  --absent-metrics-driver-info-expose-nan
  --absent-metrics-driver-info-expose-total-counter
  --absent-metrics-driver-info-expose-detailed-info
  --absent-metrics-generic-info-expose-nan
  --absent-metrics-generic-info-expose-total-counter
  --absent-metrics-generic-info-expose-detailed-info
  --no-absent-metrics-module-info-expose-nan
  --absent-metrics-module-info-expose-total-counter
  --absent-metrics-module-info-expose-detailed-info
  --absent-metrics-statistics-expose-nan
  --absent-metrics-statistics-expose-total-counter
  --absent-metrics-statistics-expose-detailed-info

Metrics processing settings:
  --no-statistics-generate-missing-per-queue-metrics
    Generate missing metrics per queue if missing (eg in Broadcom bnxt_en driver)
  --list-label-format=multi-label
    How to transform lists of strings to prometheus labels. Possible values are: single-label, multi-label, both

`
