---
name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: googleapis/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        with:
          release-type: go
          package-name: go-ethtool-exporter

  create-github-release:
    needs: release-please
    runs-on: ubuntu-22.04
    if: github.ref_type == 'tag'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with:
          path: dist
          merge-multiple: true

      - name: Upload binaries to release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: dist/**
