---
name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        id: release
        with:
          release-type: go
          package-name: go-ethtool-exporter

  build-release-binaries:
    runs-on: ubuntu-24.04
    if: |
      contains(github.event.head_commit.message, '(main): release')
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    strategy:
      matrix:
        GOARCH: [arm64, amd64]
    env:
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build binary
        run: go build -o "go-ethtool-exporter-${GOARCH}"
      - uses: actions/upload-artifact@v4.6.2
        with:
          if-no-files-found: error
          # Env-variables don't really work in "actions/upload-artifact", thats why we use pipeline-level templating
          name: "go-ethtool-exporter-${{ matrix.GOARCH }}"
          path: "go-ethtool-exporter-${{ matrix.GOARCH }}"

  upload-release-binaries:
    needs: [build-release-binaries, release-please]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/download-artifact@v4.3.0
        with:
          path: dist
          merge-multiple: true
      - run: gh release upload ${{ needs.release-please.outputs.tag_name }} dist/*
        env:
          GH_TOKEN: ${{ github.token }}
