---
name: Test and build
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-n-build
  cancel-in-progress: true

env:
  GOOS: linux
  COVERAGE_THRESHOLD: 78.2

jobs:
  test:
    # Release-please causes us to have two commits in the main branch.
    # We don't want to run tests on second (release) commit.
    if: |
      !contains(github.event.head_commit.message, '(main): release')
    runs-on: ubuntu-24.04
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run tests
        run: go test ./... -coverprofile coverage.out
      - name: Show coverage report per-function
        run: go tool cover -func coverage.out
      # TODO: set coverage threshold, eg https://github.com/lluuiissoo/go-testcoverage/blob/main/.github/workflows/ci.yml
      - name: Check total coverage threshold
        run: |
              echo "Coverage threshold: $COVERAGE_THRESHOLD %"
              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
              echo "Current test coverage: $totalCoverage %"
              if awk "BEGIN {exit !($totalCoverage >= $COVERAGE_THRESHOLD)}"; then
                  echo "OK"
              else
                  echo "Current test coverage is below threshold"
                  exit 1
              fi

  build:
    runs-on: ubuntu-24.04
    needs: [test]
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    strategy:
      matrix:
        GOARCH: [arm64, amd64]
    env:
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build binary
        run: go build -o "go-ethtool-exporter-${GOARCH}"
      - uses: actions/upload-artifact@v4.6.2
        with:
          if-no-files-found: error
          # Env-variables don't really work in "actions/upload-artifact", thats why we use pipeline-level templating
          name: "go-ethtool-exporter-${{ matrix.GOARCH }}"
          path: "go-ethtool-exporter-${{ matrix.GOARCH }}"
